CC = gcc
CFLAGS = -g -Wall -std=gnu99
CFLAG2 = -c -Wall -std=gnu99
OBJETS = client1.o 

all: client1

client1: $(OBJETS)
	$(CC) $(CFLAGS) $(OBJETS) -o client1

client1.o: client1.c client1.h
	$(CC) $(CFLAG2) client1.c -o client1.o

clean:
	@rm -f *~ *.o client1
